name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: login
      
    - name: Build the Docker image
      run: docker build ./frontend --file ./frontend/Dockerfile --tag frontend

    - name: Push the Docker image
      run: docker push junsoo0414/auto-minder-ai:frontend

